version: "3"
services:
  styleguidebuilder:
    command: npm run start:dev
    ports:
        - 443:3000
        - 80:2000
    volumes:
      - server_volume_sync:/app:nocopy
      - views_volume_sync:/app/views:nocopy
      - ./certs/fullchain.pem:/etc/letsencrypt/live/andreanaya.com/fullchain.pem
      - ./certs/privkey.pem:/etc/letsencrypt/live/andreanaya.com/privkey.pem

volumes:
  server_volume_sync:
    external: true
  views_volume_sync:
    external: true